import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import { Poller_One } from "next/font/google";

import Footer from "@/components/ui/Footer";
import { auth } from "@/auth.config";
import { redirect } from "next/navigation";

const roboto = Poller_One({
  subsets: ["latin"],
  weight: "400", // Poller One solo tiene un peso disponible
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (session?.user) {
    redirect("/");
  }
  return (
    <main className="flex flex-col min-h-screen justify-center items-center p-4 sm:p-6 ">
      {/* 
        Este div envuelve el contenido principal (por ejemplo, el formulario de login).
        Se le asigna un `max-w-md` (aproximadamente 448px) para una mejor legibilidad y estética 
        en pantallas grandes, y `w-full` para que ocupe el ancho disponible en pantallas más pequeñas,
        asegurando que el contenido esté centrado. La clase `roboto.className` aplica la fuente Poller_One.
      */}
      <div className={`w-full max-w-md ${roboto.className}`}>{children}</div>
    </main>
  );
}
