import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "../globals.css";

import { Poller_One } from "next/font/google";
import { TopMenu } from "@/components/ui/TopMenu";
import SideBar from "@/components/ui/SideBar";
import Footer from "@/components/ui/Footer";

const roboto = Poller_One({
  subsets: ["latin"],
  weight: "400", // Poller One solo tiene un peso disponible
  display: "swap",
});

/* const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
}); */

export const metadata: Metadata = {
  title: "SHOP",
  description: "Generated by create next app",
};

export default function ShopLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <TopMenu />
      <SideBar />
      <div className={roboto.className}>{children}</div>
      <Footer />
    </main>
  );
}
