import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Poller_One } from "next/font/google";
import Providers from "@/components/providers/Providers";
import Head from "next/head"; //

import { unstable_ViewTransition as ViewTransition } from "react";

const roboto = Poller_One({
  subsets: ["latin"],
  weight: "400", // Poller One solo tiene un peso disponible
  display: "swap",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "😊 | %s",
    default: "home",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <script
          src={`https://www.google.com/recaptcha/api.js?render=${process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}`}
          async
          defer
        ></script>
      </Head>

      <body className={roboto.className}>
        <Providers>
          <ViewTransition>{children}</ViewTransition>
        </Providers>
      </body>
    </html>
  );
}
